language: python
sudo: false

cache:
  pip: true
  directories:
    - .tox

python:
  - 2.7

install:
  - pip install -U -r requirements.txt
  - pip install -U tox-travis coveralls
script:
  - tox
after_success:
  - coveralls
