language: python
sudo: required

cache:
  pip: true
  directories:
    - .tox

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install tox-travis coveralls
script:
  - tox
after_success:
  - coveralls
